### ISSUE TITLE
multiple definitions of many functions

### ISSUE THREAD

**Issue by Jestar342** [whoop-t/nice-shield-base#1]
Hi,

I followed your guide for custom art. I've triple checked every stage and I can't see any obvious error, but I'm getting errors in build: https://github.com/Jestar342/zmk-config/actions/runs/14451565738/job/40525298147

my config: https://github.com/jestar342/zmk-config
my shield: https://github.com/jestar342/nice-shield-spacemarine

I'm very new to ZMK and C so not sure what's gone wrong :)

**Comment by whoop-t** [comment]
@Jestar342 Ill take a look later tonight and see if I can get it working on my keyboard

**Comment by whoop-t** [comment]
@Jestar342 Your shield repo worked for me.

I think your issue is in your zmk-config, `build.yaml`

You have this, but idk where you got `nice_view` from
```yaml
include:
  - board: nice_nano_v2
    shield: sofle_left nice_view_adapter nice_view nice_shield_spacemarine
  - board: nice_nano_v2
    shield: sofle_right nice_view_adapter nice_view nice_shield_spacemarine
```

Change to this and try again
```yaml
include:
  - board: nice_nano_v2
    shield: sofle_left nice_view_adapter nice_shield_spacemarine
  - board: nice_nano_v2
    shield: sofle_right nice_view_adapter nice_shield_spacemarine
```

Also note that I am testing this on a corne, but I dont think that matters

I see your image on the right half but its broken, it might not be rotated correctly.
